var False = 'Wrong!';
var True = 'Correct';

//array for the questions to be asked on the page
var quizquestions =[
    {
question: "Commonly used data types DON'T Include:",
1.: "Strings",
2.: "Booleans",
3.: "Alerts",
4.: "Numbers",
    },
    {
        question: "The condition in an if/else statement is enclosed with__________.",
        1.: "Quotes",
        2.: "Curly Brackets",
        3.: "Parenthesis",
        4.: "Square Brackets",
        //correct answer 3.
    },
    {
        question: "Arrays in Javascript can be used to store______.",
        1.: "Numbers and Strings",
        2.: "Other Arrays",
        3.: " Booleans",
        4,: "All of the Above",
        //correct answer 4
    }
    {
        question: "String values must be enclosed within ____ when being assigned to variables.",
        1.: "Commas",
        2.: "Curly Brackets",
        3.: "Quotes",
        4.: "Parenthesis",
        //correct answer
    }

    {
        question: "A very useful tool used during development and debugging for printing content to the debugger is:",
        1.: "Javascript",
        2.: "Terminal/Bash",
        3.: "For Loops",
        4.: "Console.log",
        //correct answer 4
    }
];

//function to start the quiz
